version: '3.4'

services:
 nginx:
  image: nginx
  depends_on:
   - minio1
   - minio2
   - minio3
   - minio4
  networks:
   - minio_distributed
  ports:
   - "9000:80"
  volumes:
   - ./nginx/nginx-minio.conf:/etc/nginx/conf.d/default.conf

 minio1:
  image: minio/minio
  volumes:
   - data1:/data
  networks:
   - minio_distributed
  ports:
   - "9000"
  hostname: minio1
  environment:
   MINIO_ACCESS_KEY: minio-artificerpi
   MINIO_SECRET_KEY: minio-passw0rd
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
  
 minio2:
  image: minio/minio
  volumes:
   - data2:/data
  networks:
   - minio_distributed
  ports:
   - "9000"
  hostname: minio2
  environment:
   MINIO_ACCESS_KEY: minio-artificerpi
   MINIO_SECRET_KEY: minio-passw0rd
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

 minio3:
  image: minio/minio
  volumes:
   - data3:/data
  networks:
   - minio_distributed
  ports:
   - "9000"
  hostname: minio3
  environment:
   MINIO_ACCESS_KEY: minio-artificerpi
   MINIO_SECRET_KEY: minio-passw0rd
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

 minio4:
  image: minio/minio
  volumes:
   - data4:/data
  networks:
   - minio_distributed
  ports:
   - "9000"
  hostname: minio4
  environment:
   MINIO_ACCESS_KEY: minio-artificerpi
   MINIO_SECRET_KEY: minio-passw0rd
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

volumes:
  data1:
  data2:
  data3:
  data4:

networks:
 minio_distributed:
  driver: overlay

